###############################################################################
# This is default configuration.

version: 0.6 

######################################################
## neural network 

# network definition
network_type: 0        # refer to neural_net/const.py
lstm: False

# training
# data_shuffle: True
validation_rate: 0.3
num_epochs: 20
batch_size: 16
num_outputs: 1

# steering data preprocessing
# - steering angle adjustment
steering_angle_scale: 5.0
# - steering wheel jitter tolerance
steering_angle_jitter_tolerance: 0.01

# driving simulator
steering_angle_max: 450
steering_angle_tolerance: 0.015 # around 7.5 degree

# data augmentation
data_aug_flip: True
data_aug_bright: True
data_aug_shift: True

# input image size to the neural network
input_image_width: 160
input_image_height: 160
input_image_depth: 3

######################################################
## data collection

# vehicle name
vehicle_name: fusion
# camera image topic 
camera_image_topic: /fusion/front_camera/image_raw
# vehicle control topic name
vehicle_control_topic: /fusion

# crop (capture) area from a camera image
# - gazebo simulated camera resolution: 800x800
image_crop_x1: 0
image_crop_y1: 375
image_crop_x2: 800
image_crop_y2: 585