###############################################################################
# This is a Aws's configuration.

version: 0.91

# history
# 0.91 - add num_inputs, use 2 for num_outputs

######################################################
## neural network

# network definition
network_type:   4       # refer to neural_net/const.py
lstm:           False
ndpia:          False
ndpia_DNN:      False
custom_loss:    False

str_out:      False    # applicable if network type is 6
thr_out:      False   # applicable if network type is 6 or 7
brk_out:      False   # applicable if network type is 6 or 7


lstm_timestep: 1
lstm_lr:       0.00001      
cnn_lr:        0.0001         # default of Adam is 0.001

# normalize data
normalize_data: False

# training
# data_shuffle: True
validation_rate:         0.2
num_epochs:              50
batch_size:              32
num_inputs:              3    # if 2 --> input: [image, velocity] or [velocity, acceleration] 
                              # if 3 --> input: [image, velocity, acceleration] 
num_outputs:             3    # output: steering_angle, throttle
early_stopping_patience: 3

# tensorboard log dir
tensorboard_log_dir: logs/scalars/

# data augmentation
data_aug_flip: True
data_aug_bright: True
data_aug_shift: False

# input image size to the neural network
input_image_width:  160
input_image_height: 160
input_image_depth:  3

# steering data preprocessing
# - steering angle adjustment
steering_angle_scale:            1.0
# - steering wheel jitter tolerance
steering_angle_jitter_tolerance: 0.01
