###############################################################################
# This is default configuration.

version: 0.6

######################################################
## neural network 

# network definition
network_type: 0        # refer to neural_net/const.py
lstm: False

# normalize data
normalize_data: True

# training
# data_shuffle: True
validation_rate: 0.3
num_epochs: 20
batch_size: 16
num_outputs: 1
early_stopping_patience: 3
# tensorboard log dir
tensorboard_log_dir: logs/scalars/

# steering data preprocessing
# - steering angle adjustment
steering_angle_scale: 1.0
# - steering wheel jitter tolerance
steering_angle_jitter_tolerance: 0.01

# driving simulator
steering_angle_max: 450
steering_angle_tolerance: 0.015 # around 7.5 degree

# data augmentation
data_aug_flip: False
data_aug_bright: True
data_aug_shift: True

# input image size to the neural network
input_image_width: 160
input_image_height: 160
input_image_depth: 3

######################################################
## data collection

# image cropping: True for legacy datasets. 
#                 False for new datasets.
crop: False

# vehicle name
vehicle_name: rover
# camera image topic 
camera_image_topic: /camera/image_raw
# vehicle control topic name
vehicle_control_topic: /rover
# p3d - current position and velocity
base_pose_topic: /mavros/global_position/local

# crop (capture) area from a camera image
# - gazebo simulated camera resolution: 800x600
image_crop_x1: 0
image_crop_y1: 180
image_crop_x2: 799
image_crop_y2: 350

######################################################
## driving strategy - run_neural.py

# steering angle value for sharp turn
sharp_turn_min: 0.3
# when sharp turn, apply brake for this sec.
brake_apply_sec: 1.7
# throttle at non sharp turn
throttle_default: 0.15
# throttle at sharp turn
throttle_sharp_turn: 0.05
# velocity threshold for not moving
velocity_0: 0.03
